/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1alpha1

import (
	nahid_try_com_v1alpha1 "k8s-crd-controller/pkg/apis/nahid.try.com/v1alpha1"
	versioned "k8s-crd-controller/pkg/client/clientset/versioned"
	internalinterfaces "k8s-crd-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "k8s-crd-controller/pkg/client/listers/nahid.try.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// PodWatchInformer provides access to a shared informer and lister for
// PodWatchs.
type PodWatchInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.PodWatchLister
}

type podWatchInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPodWatchInformer constructs a new informer for PodWatch type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPodWatchInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPodWatchInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPodWatchInformer constructs a new informer for PodWatch type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPodWatchInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NahidV1alpha1().PodWatchs(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NahidV1alpha1().PodWatchs(namespace).Watch(options)
			},
		},
		&nahid_try_com_v1alpha1.PodWatch{},
		resyncPeriod,
		indexers,
	)
}

func (f *podWatchInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPodWatchInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *podWatchInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&nahid_try_com_v1alpha1.PodWatch{}, f.defaultInformer)
}

func (f *podWatchInformer) Lister() v1alpha1.PodWatchLister {
	return v1alpha1.NewPodWatchLister(f.Informer().GetIndexer())
}
