apiVersion: admissionregistration.k8s.io/v1alpha1
kind: InitializerConfiguration
metadata:
  name: podwatch-initializer-config
initializers:
  # the name needs to be fully qualified, i.e., containing at least two "."
  - name: podwatchinit.nahid.try.com
    rules:
      # apiGroups, apiVersion, resources all support wildcard "*".
      # "*" cannot be mixed with non-wildcard.
      - apiGroups:
          - nahid.try.com
        apiVersions:
          - v1alpha1
        resources:
          - podwatchs